version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
      - "8080:8080"
    command: tail -f /dev/null
    restart: unless-stopped
  mysql:
    image: mysql:8.0
    env_file:
      - dev.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: 