controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

e01bundle:
    resource: ../src/E01Bundle/Controller/
    type: attribute
e02bundle:
    resource: ../src/E02Bundle/Controller/
    type: attribute
e03bundle:
    resource: ../src/E03Bundle/Controller/
    type: attribute
e04bundle:
    resource: ../src/E04Bundle/Controller/
    type: attribute
e05bundle:
    resource: ../src/E05Bundle/Controller/
    type: attribute
